url: /static/

directory: ../static/

bundles:
    base-js:
        output: bundle/base.js
        contents:
            - external/jquery.min.js
            - external/bootstrap/js/bootstrap.min.js
            - external/bootflat/js/icheck.min.js
            - external/bootflat/js/jquery.fs.selecter.min.js
            - external/bootflat/js/jquery.fs.stepper.min.js
            - utils.js

    base-css:
        output: bundle/base.css
        filters: cssrewrite
        contents:
            - external/bootstrap/css/bootstrap.min.css
            - external/bootflat/css/bootflat.min.css
            - stylesheets/styles.css

    fonts-css:
        output: bundle/fonts.css
        filters: cssrewrite
        contents:
            - fonts/fonts.css


    main-js:
        output: bundle/main.js
        contents:
            - base-js
            - external/jquery-ui.min.js
            - external/jquery.selectBoxIt.min.js
            - flash_message.js
            - times_and_sizes_formatter.js
            - recordings_model.js
            - collections_model.js
            - recordings.js
            - external/validator.js
            - containerized_ui.js
            - extract_ui.js

    main-css:
        output: bundle/main.css
        contents:
            - fonts-css
            - base-css
            - external/jquery.selectBoxIt.css
            - stylesheets/footer.css


    user-js:
        output: bundle/index.js
        filters: cssrewrite
        contents:
            - external/bootstrap-switch.js
            - uploader.js
            - newrecording.js
            - user.js
            - editor.js
            - external/marked.min.js
            - external/bootstrap-markdown.js

    user-css:
        output: bundle/index.css
        contents:
            - external/bootstrap-switch.css
            - external/bootstrap-markdown.min.css

    wb-frame-js:
        output: bundle/wb_frame.js
        contents:
            - pkg://pywb/static/wb_frame.js

    frame-js:
        output: bundle/frame.js
        contents:
            - base-js
            - pkg://pywb/static/wb_frame.js
            - times_and_sizes_formatter.js
            - collections_model.js
            - recordings_model.js
            - recordings.js
            - automate.js
            - containerized_ui.js
            - external/bootstrap-switch.js
            - extract_ui.js

    frame-css:
        output: bundle/frame.css
        contents:
            - fonts-css
            - base-css
            - external/bootstrap-switch.css
            - pkg://pywb/static/scroll-webkit.css


    coll-js:
        output: bundle/coll.js
        contents:
            - external/jquery-ui.min.js
            - external/bootstrap-switch.js
            - external/bootstrap-table.min.js

            - external/marked.min.js
            - external/bootstrap-markdown.js

            - external/jquery.dataTables.min.js
            - external/dataTables.bootstrap.js

            - editor.js
            - collection_info.js
            - edit_title_in_place.js

            - uploader.js

    coll-css:
        output: bundle/coll.css
        contents:
            - external/bootstrap-switch.css
            - external/bootstrap-table.min.css
            - external/bootstrap-markdown.min.css
            - external/dataTables.bootstrap.css

    pywb-js:
        output: bundle/pywb.js
        contents:
            - pkg://pywb/static/wombat.js
            - pkg://pywb/static/vidrw.js
            - wrscripts.js
            #- embedMiniBehavior.js

    wombatWorkers-js:
        output: bundle/wombatWorkers.js
        contents:
            - pkg://pywb/static/wombatWorkers.js

    autoFetchWorker-js:
        output: bundle/autoFetchWorker.js
        contents:
            - pkg://pywb/static/autoFetchWorker.js

    proxy-js:
        output: bundle/proxy.js
        contents:
            - pkg://pywb/static/wombatProxyMode.js
            - wrscripts.js
            - ws.js
            #- embedMiniBehavior.js

    browser-js:
        output: bundle/browser.js
        contents:
            - base-js
            - times_and_sizes_formatter.js
            - browser_embed.js
            - recordings_model.js
            - collections_model.js
            - recordings.js
            - automate.js
            - containerized_ui.js
            - external/bootstrap-switch.js
            - extract_ui.js

    browser-css:
        output: bundle/browser.css
        contents:
            - external/bootstrap-switch.css

    paging-js:
        output: bundle/paging.js
        contents:
            - paging.js


